### PR TITLE
Diagram upload for readme

### PR DESCRIPTION
**Pull request by zafileo23**

### CODE REVIEW

**Comment by 0xaaiden** [comment]
What software did you use for the diagram

**Comment by zafileo23** [comment]
> What software did you use for the diagram

I made it in [Lucid Chart](https://www.lucidchart.com/pages/) @0xaaiden

**Comment by 0xaaiden** [comment]
Thanks @zafileo23, would it be possible to get the exported diagram for modifications?

**Comment by zafileo23** [comment]
> 

Sure, here is a link to a copy of the chart which you should be able to edit: [Copy of textSQL](https://lucid.app/lucidchart/2fb2b3b7-75fe-44f1-8478-3c40a90371a3/edit?invitationId=inv_a2375ccd-fd0b-4cd6-8118-5f7d6f293852)

You can also probably export from the link as well @0xaaiden

**Comment by 0xaaiden** [comment]
Thanks @zafileo23, appreciate it!

**Pull request closed without merging**
